import { useCallback } from "react";
import { useAuthStore } from "@/store";
import { hasPermission as hasPermissionCode } from "@/lib/permissions";

export type ClientAction =
  | "READ"
  | "CREATE"
  | "UPDATE"
  | "DELETE"
  | "ACTIVATE"
  | "REJECT"
  | "WITHDRAW"
  | "REACTIVATE"
  | "CLOSE"
  | "UNDO_REJECT"
  | "UNDO_WITHDRAWAL"
  | "ASSIGN_STAFF"
  | "UNASSIGN_STAFF"
  | "UPDATE_SAVINGS_ACCOUNT"
  | "PROPOSE_TRANSFER"
  | "ACCEPT_TRANSFER"
  | "REJECT_TRANSFER"
  | "WITHDRAW_TRANSFER"
  | "READ_IMAGE"
  | "CREATE_IMAGE"
  | "DELETE_IMAGE"
  | "READ_NOTE"
  | "CREATE_NOTE"
  | "UPDATE_NOTE"
  | "DELETE_NOTE"
  | "READ_IDENTIFIER"
  | "CREATE_IDENTIFIER"
  | "UPDATE_IDENTIFIER"
  | "DELETE_IDENTIFIER"
  | "READ_CHARGE"
  | "CREATE_CHARGE"
  | "DELETE_CHARGE"
  | "WAIVE_CHARGE"
  | "PAY_CHARGE"
  | "UPDATE_CHARGE"
  | "READ_TRANSACTION"
  | "UNDO_TRANSACTION"
  | "READ_ADDRESS"
  | "CREATE_ADDRESS"
  | "UPDATE_ADDRESS"
  | "DELETE_ADDRESS"
  | "READ_DOCUMENT"
  | "CREATE_DOCUMENT"
  | "UPDATE_DOCUMENT"
  | "DELETE_DOCUMENT"
  | "READ_FAMILYMEMBER"
  | "READ_COLLATERAL"
  | "CREATE_COLLATERAL"
  | "UPDATE_COLLATERAL"
  | "DELETE_COLLATERAL";

export const CLIENT_ACTION_PERMISSIONS: Record<ClientAction, string> = {
  READ: "READ_CLIENT",
  CREATE: "CREATE_CLIENT",
  UPDATE: "UPDATE_CLIENT",
  DELETE: "DELETE_CLIENT",
  ACTIVATE: "ACTIVATE_CLIENT",
  REJECT: "REJECT_CLIENT",
  WITHDRAW: "WITHDRAW_CLIENT",
  REACTIVATE: "REACTIVATE_CLIENT",
  CLOSE: "CLOSE_CLIENT",
  UNDO_REJECT: "UNDOREJECT_CLIENT",
  UNDO_WITHDRAWAL: "UNDOWITHDRAWAL_CLIENT",
  ASSIGN_STAFF: "ASSIGNSTAFF_CLIENT",
  UNASSIGN_STAFF: "UNASSIGNSTAFF_CLIENT",
  UPDATE_SAVINGS_ACCOUNT: "UPDATESAVINGSACCOUNT_CLIENT",
  PROPOSE_TRANSFER: "PROPOSETRANSFER_CLIENT",
  ACCEPT_TRANSFER: "ACCEPTTRANSFER_CLIENT",
  REJECT_TRANSFER: "REJECTTRANSFER_CLIENT",
  WITHDRAW_TRANSFER: "WITHDRAWTRANSFER_CLIENT",
  READ_IMAGE: "READ_CLIENTIMAGE",
  CREATE_IMAGE: "CREATE_CLIENTIMAGE",
  DELETE_IMAGE: "DELETE_CLIENTIMAGE",
  READ_NOTE: "READ_CLIENTNOTE",
  CREATE_NOTE: "CREATE_CLIENTNOTE",
  UPDATE_NOTE: "UPDATE_CLIENTNOTE",
  DELETE_NOTE: "DELETE_CLIENTNOTE",
  READ_IDENTIFIER: "READ_CLIENTIDENTIFIER",
  CREATE_IDENTIFIER: "CREATE_CLIENTIDENTIFIER",
  UPDATE_IDENTIFIER: "UPDATE_CLIENTIDENTIFIER",
  DELETE_IDENTIFIER: "DELETE_CLIENTIDENTIFIER",
  READ_CHARGE: "READ_CLIENTCHARGE",
  CREATE_CHARGE: "CREATE_CLIENTCHARGE",
  DELETE_CHARGE: "DELETE_CLIENTCHARGE",
  WAIVE_CHARGE: "WAIVE_CLIENTCHARGE",
  PAY_CHARGE: "PAY_CLIENTCHARGE",
  UPDATE_CHARGE: "UPDATE_CLIENTCHARGE",
  READ_TRANSACTION: "READTRANSACTION_CLIENT",
  UNDO_TRANSACTION: "UNDOTRANSACTION_CLIENT",
  READ_ADDRESS: "READ_ADDRESS",
  CREATE_ADDRESS: "CREATE_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",
  READ_DOCUMENT: "READ_DOCUMENT",
  CREATE_DOCUMENT: "CREATE_DOCUMENT",
  UPDATE_DOCUMENT: "UPDATE_DOCUMENT",
  DELETE_DOCUMENT: "DELETE_DOCUMENT",
  READ_FAMILYMEMBER: "READ_FAMILYMEMBERS",
  READ_COLLATERAL: "READ_COLLATERAL",
  CREATE_COLLATERAL: "CREATE_COLLATERAL",
  UPDATE_COLLATERAL: "UPDATE_COLLATERAL",
  DELETE_COLLATERAL: "DELETE_COLLATERAL",
};

export function useClientPermissions() {
  const permissions = useAuthStore((s) => s.user?.permissions ?? []);

  const hasPermission = useCallback(
    (action: ClientAction) => {
      const code = CLIENT_ACTION_PERMISSIONS[action];
      return hasPermissionCode(permissions, code);
    },
    [permissions],
  );

  return { hasPermission, permissions };
}
